[Core] GasLimit estimation fixed
vultisig/vultisig-ios pull request #1533
Opened 2024-11-12 16:32 UTC by flypaper0

2024-11-12 22:12 UTC, johnnyluo requested changes
This cause problem for none EVM chains, please do some tests with 
1. EVM 
2. THORChain
3. UTXO chain 
etc etc.

2024-11-12 22:12 UTC, johnnyluo commented on VultisigApp/VultisigApp/Services/BlockChainService.swift
> -        guard !tx.coin.isNativeToken, tx.coin.chainType == .EVM else {
this break none EVM chains

2024-11-13 19:06 UTC, flypaper0 commented on VultisigApp/VultisigApp/Services/BlockChainService.swift
> -        guard !tx.coin.isNativeToken, tx.coin.chainType == .EVM else {
fixed non evm chains

2024-11-13 20:58 UTC, johnnyluo approved these changes
LGTM

2024-11-13 20:58 UTC, merged