[Backup] Monthly reminder
vultisig/vultisig-ios pull request #1561
Opened 2024-11-19 11:11 UTC by flypaper0

2024-11-19 22:30 UTC, johnnyluo commented on VultisigApp/VultisigApp/Views/Vault/VaultDetailView.swift
> +        guard !vault.isBackedUp else { return }
regardless whether a vault has been backup before , we always need to remind user monthly

2024-11-19 22:32 UTC, johnnyluo requested changes
can you please remove `!vault.isBackedUp` check?

2024-11-19 22:38 UTC, johnnyluo commented on VultisigApp/VultisigApp/Views/Vault/VaultDetailView.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
somehow this doesn't actually get called

2024-11-20 08:04 UTC, flypaper0 commented
> can you please remove `!vault.isBackedUp` check?

why we should? It make sense to me to not show it when vault is backed up

2024-11-20 08:07 UTC, flypaper0 commented on VultisigApp/VultisigApp/Views/Vault/VaultDetailView.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
it should, placed breakpoint, In 10 from 10 runs it was called

2024-11-20 08:27 UTC, johnnyluo commented
> > can you please remove `!vault.isBackedUp` check?
> 
> why we should? It make sense to me to not show it when vault is backed up

Even user did their backup , they can forget where they put it , or lost it or whatever , this remind will trigger them to double check , or maybe backup it again .

2024-11-20 08:30 UTC, flypaper0 commented
> > > can you please remove `!vault.isBackedUp` check?
> > 
> > 
> > why we should? It make sense to me to not show it when vault is backed up
> 
> Even user did their backup , they can forget where they put it , or lost it or whatever , this remind will trigger them to double check , or maybe backup it again .

ok, I see

2024-11-21 21:15 UTC, johnnyluo approved these changes
LGTM

2024-11-21 21:18 UTC, merged