[Core] Matic to pol
vultisig/vultisig-ios pull request #1653
Opened 2024-12-09 15:10 UTC by flypaper0

2024-12-09 23:15 UTC, johnnyluo commented on VultisigApp/VultisigApp/View Models/VaultDetailViewModel.swift
> +    func migrate(vault: Vault) {
can you do a data migration with swiftdata?

2024-12-10 01:41 UTC, johnnyluo commented on VultisigApp/VultisigApp/Views/Vault/VaultDetailView.swift
> +            viewModel.migrate(vault: vault)
this is checking everytime when user open the vault , which is not good

2024-12-11 16:01 UTC, enriquesouza commented
@flypaper0 @johnnyluo I've checked that and I would recommend us to not migrate like this. Only create a new Token called POL, pretty much duplicate the Matic. We have a bunch of old wallets and those wallets are using MATIC. If we rename it they will need to remove it and re add it. Or as you are doing a swift data migration it is way more risky than simply create both of them. Coingecko also does that because they have different market cap and tickers. 

So I recommend us to duplicate Matic. Another issue is that all devices must match and once we deploy on IOS we won't be able to sign Android against IOS or Win.

2024-12-11 16:02 UTC, enriquesouza requested changes
Please check my comments.

2025-01-08 21:28 UTC, johnnyluo commented
Let's close this one for now then

2025-01-08 21:28 UTC, closed without merging