Public key qr
vultisig/vultisig-ios pull request #910
Opened 2024-07-18 15:24 UTC by Rockindash

Added QR Code to show vault public keys, Issue #836 and #849

2024-07-18 20:13 UTC, flypaper0 approved these changes

2024-07-18 23:42 UTC, johnnyluo requested changes
see comments

2024-07-18 23:42 UTC, johnnyluo commented on VultisigApp/VultisigApp/Views/Components/VaultDetailQRCode.swift
> +        let id = "sha256(\(name) - \(ecdsaKey) - \(eddsaKey) - \(hexCode))"
@Rockindash , id , I mean we should compute the SHA256 hash of "name-ecdsakey-eddsakey-hexode" , not plain text

2024-07-19 00:00 UTC, enriquesouza requested changes

2024-07-19 00:00 UTC, enriquesouza commented on VultisigApp/VultisigApp/Views/Components/VaultDetailMacQRCode.swift
> +        let id = "sha256(\(name) - \(ecdsaKey) - \(eddsaKey) - \(hexCode))"
sha256 is a function to hash the id. This way, it will be as string. Can you double-check that?

2024-07-19 04:16 UTC, johnnyluo commented on VultisigApp/VultisigApp/Views/Components/VaultDetailQRCode.swift
> +        let data = """
This generate a string , which is not a valid json , can we please define a struct , and use json encode?

2024-07-19 05:45 UTC, johnnyluo approved these changes
LGTM

2024-07-19 05:54 UTC, enriquesouza approved these changes
LGTM

2024-07-19 05:54 UTC, merged